"""NES-PERF-1: the generated private-entry lookup must stay indexed.

The NES emulator makes ~9,900 private-image entries per frame; a linear scan of
kPrivateDispatchTable (7,836 rows) was ~75% of the frame. The corpus must be
generated by a GBARecomp revision that binary-searches a sorted key index, and
the index must describe exactly the private table (same entries, first match).
"""
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TABLE = ROOT / "generated" / "dispatch_table.cpp"
CMAKE = (ROOT / "CMakeLists.txt").read_text()
GENERATE = (ROOT / "scripts" / "generate-m1.sh").read_text()


@unittest.skipUnless(TABLE.is_file(), "generated corpus not present")
class PrivateLookupIndex(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = TABLE.read_text()
        priv = cls.text.split("kPrivateDispatchTable[] = {", 1)[1]
        priv = priv.split("kPrivateDispatchTableLen", 1)[0]
        cls.rows = re.findall(
            r"\{0x([0-9A-F]{8})u, (\d)u, (\d)u, (\d+)u, \w+\}", priv)
        cls.keys = [int(k, 16) for k in re.findall(
            r"^\s+0x([0-9A-F]+)ull,$",
            cls.text.split("kPrivateIndexKey[] = {", 1)[1].split("};", 1)[0], re.M)]
        cls.slots = [int(s) for s in re.findall(
            r"^\s+(\d+)u,$",
            cls.text.split("kPrivateIndexSlot[] = {", 1)[1].split("};", 1)[0], re.M)]

    def test_lookup_is_not_a_linear_scan(self):
        fn = self.text.split("int runtime_invoke_private_entry_in_image", 1)[1]
        fn = fn.split("runtime_invoke_private_entry(", 1)[0]
        self.assertNotIn("kPrivateDispatchTableLen; ++i", fn)
        self.assertIn("kPrivateIndexKey", fn)

    def test_index_matches_table_exactly(self):
        self.assertGreater(len(self.rows), 7000)
        self.assertEqual(len(self.keys), len(self.rows))
        self.assertEqual(len(self.slots), len(self.rows))
        self.assertEqual(self.keys, sorted(self.keys))
        for key, slot in zip(self.keys, self.slots):
            addr, thumb, _resume, image = self.rows[slot]
            self.assertEqual(key, (int(image) << 33) | (int(thumb) << 32) | int(addr, 16))
        self.assertEqual(sorted(self.slots), list(range(len(self.rows))))

    def test_first_match_wins_on_duplicates(self):
        last = {}
        for key, slot in zip(self.keys, self.slots):
            if key in last:
                self.assertGreater(slot, last[key], "duplicate keys must keep table order")
            last[key] = slot


class PinConsistency(unittest.TestCase):
    def test_cmake_and_generator_pin_agree(self):
        cm = re.search(r'set\(MZM_GBARECOMP_PIN "([0-9a-f]{40})"', CMAKE).group(1)
        sh = re.search(r"MZM_GBARECOMP_PIN:-\$\{PIN:-([0-9a-f]{40})\}", GENERATE).group(1)
        self.assertEqual(cm, sh)


if __name__ == "__main__":
    unittest.main()
