#!/usr/bin/env python3
"""
Expands the versioned canonical NES emulator map (configs/nes-emulator-map-us.toml)
into the artifacts the build consumes:

  --config-out PATH   gba_recompile config: [[executable_image]] (image-scoped
                      overlays), [[data_range]] and [[extra_func]] blocks
  --header-out PATH   C++ header with code runs, verification scopes (byte-gate
                      runs, digests, direct-transfer requirements) used by the
                      runtime/test byte gate (needs --parts-dir). Scopes are MZM
                      policy only: they never reach --config-out.

No nested ELF, decomp build or external scratch data is needed: the canonical
map plus the Part images extracted from the legal ROM
(scripts/extract-nes-emulator.py) are sufficient. Output is a pure function of
those inputs (no absolute paths, timestamps or environment).

Usage:
  generate-nes-emulator-config.py --config-out .local/mzm-us-nes-emulator.toml
  generate-nes-emulator-config.py --header-out src/mzm_nes_emulator_map.h --parts-dir .local/nes-emulator
  ... --check-header src/mzm_nes_emulator_map.h   # fail if committed header is stale
"""
import argparse
import hashlib
import os
import sys
import tomllib

DEFAULT_MAP = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "configs", "nes-emulator-map-us.toml")
PARTS_REL = ".local/nes-emulator"
MAX_SCOPES = 4   # must equal mzm_nes_emulator::kMaxScopes in the resolver

CONFIG_HEADER = """\
# NES emulator executable images (M4 NES-2 / NES-2b), one image-scoped
# overlay each.
#
# GENERATED by scripts/generate-nes-emulator-config.py from the canonical map
# configs/nes-emulator-map-us.toml. Do not edit.
#
# Images are reconstructed locally from the legal ROM by
# scripts/extract-nes-emulator.py (.local/nes-emulator/partN.bin, never
# committed). This file holds addresses, modes and digests only.
#
# Every image is an overlay = true executable image, and every function and
# data range names it with image = "nes_partN". Part 2 (IWRAM) shares guest
# addresses with MZM's own IWRAM code_copy entries (gInterruptCode, sound
# code, clipdata, Chozodia); the image-scoped private CFG keeps them apart.
# The runtime enters them with runtime_invoke_private_entry_in_image().

"""


def load_map(path):
    with open(path, "rb") as f:
        m = tomllib.load(f)
    if m.get("schema") != 1:
        sys.exit(f"{path}: unsupported schema {m.get('schema')!r}")
    images = m["image"]
    for img in images:
        img["scopes"] = normalize_scopes(img)
    return images


def normalize_scopes(img):
    """Validated verification scopes of an image (implicit single scope if none).

    Scopes must tile the image exactly, `requires` must name declared scopes,
    every mutable range and seed must lie inside one scope. Returns dicts with
    id, ranges (sorted, half-open), requires (ids) and closure (ids, incl. self).
    """
    base, end = img["load_address"], img["load_address"] + img["size"]
    raw = img.get("scope") or [{"id": "image", "ranges": [[base, end]], "requires": []}]
    scopes, seen = [], set()
    for sc in raw:
        if sc["id"] in seen:
            sys.exit(f'{img["id"]}: duplicate scope {sc["id"]!r}')
        seen.add(sc["id"])
        rng = sorted((a, b) for a, b in sc["ranges"])
        if not rng or any(b <= a for a, b in rng):
            sys.exit(f'{img["id"]}: scope {sc["id"]!r} has an empty/inverted range')
        scopes.append({"id": sc["id"], "ranges": rng, "requires": list(sc.get("requires", [])),
                       "lifecycle": sc.get("lifecycle", "resident")})
    tiles = sorted(r for sc in scopes for r in sc["ranges"])
    cur = base
    for a, b in tiles:
        if a != cur:
            sys.exit(f'{img["id"]}: scopes do not tile the image at 0x{cur:08X} (next 0x{a:08X})')
        cur = b
    if cur != end:
        sys.exit(f'{img["id"]}: scopes end at 0x{cur:08X}, image ends at 0x{end:08X}')
    ids = {sc["id"] for sc in scopes}
    for sc in scopes:
        unknown = set(sc["requires"]) - ids
        if unknown or sc["id"] in sc["requires"]:
            sys.exit(f'{img["id"]}: scope {sc["id"]!r} has bad requires {sorted(unknown) or sc["id"]}')
    if len(scopes) > MAX_SCOPES:
        sys.exit(f'{img["id"]}: more than {MAX_SCOPES} scopes')
    by_id = {sc["id"]: sc for sc in scopes}
    for sc in scopes:
        clo, todo = {sc["id"]}, [sc["id"]]
        while todo:
            for r in by_id[todo.pop()]["requires"]:
                if r not in clo:
                    clo.add(r)
                    todo.append(r)
        sc["closure"] = clo
    for m in img.get("mutable", []):
        if not any(a <= m["start"] and m["end"] <= b for sc in scopes for a, b in sc["ranges"]):
            sys.exit(f'{img["id"]}: mutable range 0x{m["start"]:08X} straddles scopes')
    return scopes


def seeds_of(img):
    s = [(a, "arm") for a in img["seeds_arm"]] + [(a, "thumb") for a in img["seeds_thumb"]]
    return sorted(s)


def emit_config(images):
    out = [CONFIG_HEADER]
    for img in images:
        out.append(f'[[executable_image]]\nid = "{img["id"]}"\n'
                   f'path = "{PARTS_REL}/{img["part"]}.bin"\n'
                   f'load_address = 0x{img["load_address"]:08X}\nsize = 0x{img["size"]:X}\n'
                   f'sha256 = "{img["sha256"]}"\noverlay = true\n'
                   f'note = "NES emulator {img["part"]}"\n\n')
    for img in images:
        n, base, size = img["part"], img["load_address"], img["size"]
        out.append(f"# ---- {n}: 0x{base:08X}..0x{base + size:08X}\n")
        for a, b, m in img["runs"]:
            if m == "data":
                out.append(f'[[data_range]]\nstart = 0x{a:08X}\nend = 0x{b:08X}\n'
                           f'note = "NES {n} data/literals"\nimage = "{img["id"]}"\n\n')
        for a, m in seeds_of(img):
            out.append(f'[[extra_func]]\naddr = 0x{a:08X}\nmode = "{m}"\n'
                       f'name = "nes_{n}_{a:08x}"\ndispatch = false\n'
                       f'image = "{img["id"]}"\n\n')
    return "".join(out)


def gate_runs(img, scope):
    """Scope ranges minus the image's runtime-proven mutable ranges."""
    gate = []
    muts = sorted((m["start"], m["end"]) for m in img.get("mutable", []))
    for a, b in scope["ranges"]:
        cur = a
        for ms, me in muts:
            if me <= cur or ms >= b:
                continue
            if ms > cur:
                gate.append((cur, ms))
            cur = max(cur, me)
        if cur < b:
            gate.append((cur, b))
    return gate


def emit_header(images, parts_dir):
    out = ["// Generated by scripts/generate-nes-emulator-config.py from",
           "// configs/nes-emulator-map-us.toml + the ROM-extracted Part images.",
           "// Addresses, modes and SHA-256 digests only; no ROM-derived bytes.",
           "// A verification scope's gate = its ranges minus runtime-proven mutable data;",
           "// the gate SHA-256 covers those runs (code + literal pools baked into",
           "// generated code). requires_mask is the transitive closure of direct",
           "// transfers that leave the scope (bit i = scope i of the image, incl. self).",
           "#pragma once\n#include <cstddef>\n#include <cstdint>\n",
           "namespace mzm_nes_emulator {\n",
           "struct CodeRun { std::uint32_t start; std::uint32_t end; };",
           "",
           "struct ScopeSpec {",
           "    const char* id;",
           "    const CodeRun* pc;            // PC ownership ranges (scopes tile the image)",
           "    std::size_t pc_count;",
           "    const CodeRun* gate;          // byte runs verified for this scope",
           "    std::size_t gate_count;",
           "    const char* gate_sha256;",
           "    const char* prefilter_sha256; // first 32 gated bytes",
           "    std::uint32_t requires_mask;",
           "};\n"]
    for img in images:
        n, base, size = img["part"], img["load_address"], img["size"]
        out.append("// Code runs from the decomp mapping symbols (test classification only).")
        out.append(f"inline constexpr CodeRun k_{n}_code[] = {{")
        out += [f"    {{0x{a:08X}u, 0x{b:08X}u}}," for a, b, m in img["runs"] if m != "data"]
        out.append("};")
        with open(os.path.join(parts_dir, f"{n}.bin"), "rb") as f:
            blob = f.read()
        if len(blob) != size or hashlib.sha256(blob).hexdigest() != img["sha256"]:
            sys.exit(f"{n}: extracted image does not match canonical size/sha256")
        scopes = img["scopes"]
        order = {sc["id"]: i for i, sc in enumerate(scopes)}
        for sc in scopes:
            sid = sc["id"]
            gate = gate_runs(img, sc)
            out.append(f"inline constexpr CodeRun k_{n}_{sid}_pc[] = {{")
            out += [f"    {{0x{a:08X}u, 0x{b:08X}u}}," for a, b in sc["ranges"]]
            out.append("};")
            out.append(f"inline constexpr CodeRun k_{n}_{sid}_gate[] = {{")
            out += [f"    {{0x{a:08X}u, 0x{b:08X}u}}," for a, b in gate]
            out.append("};")
            gbytes = b"".join(blob[a - base:b - base] for a, b in gate)
            out.append(f'inline constexpr const char* k_{n}_{sid}_gate_sha256 =\n'
                       f'    "{hashlib.sha256(gbytes).hexdigest()}";')
            out.append(f'inline constexpr const char* k_{n}_{sid}_prefilter_sha256 =\n'
                       f'    "{hashlib.sha256(gbytes[:32]).hexdigest()}";')
        out.append(f"inline constexpr ScopeSpec k_{n}_scopes[] = {{")
        for sc in scopes:
            sid = sc["id"]
            mask = sum(1 << order[c] for c in sc["closure"])
            out.append(f'    {{"{sid}", k_{n}_{sid}_pc, sizeof(k_{n}_{sid}_pc) / sizeof(CodeRun),\n'
                       f'     k_{n}_{sid}_gate, sizeof(k_{n}_{sid}_gate) / sizeof(CodeRun),\n'
                       f'     k_{n}_{sid}_gate_sha256, k_{n}_{sid}_prefilter_sha256, 0x{mask:X}u}},')
        out.append("};\n")
    out.append("}  // namespace mzm_nes_emulator")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--map", default=DEFAULT_MAP)
    ap.add_argument("--config-out")
    ap.add_argument("--header-out")
    ap.add_argument("--check-header", metavar="PATH")
    ap.add_argument("--parts-dir", default=PARTS_REL)
    args = ap.parse_args()
    if not (args.config_out or args.header_out or args.check_header):
        ap.error("nothing to do")
    images = load_map(args.map)
    if args.config_out:
        os.makedirs(os.path.dirname(os.path.abspath(args.config_out)), exist_ok=True)
        with open(args.config_out, "w", newline="\n") as f:
            f.write(emit_config(images))
        print(f"config written: {args.config_out}")
    if args.header_out:
        with open(args.header_out, "w", newline="\n") as f:
            f.write(emit_header(images, args.parts_dir))
        print(f"header written: {args.header_out}")
    if args.check_header:
        want = emit_header(images, args.parts_dir)
        with open(args.check_header) as f:
            have = f.read()
        if want != have:
            print(f"STALE: {args.check_header} differs from canonical map + extracted parts")
            return 1
        print(f"header up to date: {args.check_header}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
