#!/usr/bin/env python3
"""
Expands the versioned canonical NES emulator map (configs/nes-emulator-map-us.toml)
into the artifacts the build consumes:

  --config-out PATH   gba_recompile config: [[executable_image]] (image-scoped
                      overlays), [[data_range]] and [[extra_func]] blocks
  --header-out PATH   C++ header with code runs, byte-gate runs and gate digests
                      used by the runtime/test byte gate (needs --parts-dir)

No nested ELF, decomp build or external scratch data is needed: the canonical
map plus the Part images extracted from the legal ROM
(scripts/extract-nes-emulator.py) are sufficient. Output is a pure function of
those inputs (no absolute paths, timestamps or environment).

Usage:
  generate-nes-emulator-config.py --config-out .local/mzm-us-nes-emulator.toml
  generate-nes-emulator-config.py --header-out src/mzm_nes_emulator_map.h --parts-dir .local/nes-emulator
  ... --check-header src/mzm_nes_emulator_map.h   # fail if committed header is stale
"""
import argparse
import hashlib
import os
import sys
import tomllib

DEFAULT_MAP = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "configs", "nes-emulator-map-us.toml")
PARTS_REL = ".local/nes-emulator"

CONFIG_HEADER = """\
# NES emulator executable images (M4 NES-2 / NES-2b), one image-scoped
# overlay each.
#
# GENERATED by scripts/generate-nes-emulator-config.py from the canonical map
# configs/nes-emulator-map-us.toml. Do not edit.
#
# Images are reconstructed locally from the legal ROM by
# scripts/extract-nes-emulator.py (.local/nes-emulator/partN.bin, never
# committed). This file holds addresses, modes and digests only.
#
# Every image is an overlay = true executable image, and every function and
# data range names it with image = "nes_partN". Part 2 (IWRAM) shares guest
# addresses with MZM's own IWRAM code_copy entries (gInterruptCode, sound
# code, clipdata, Chozodia); the image-scoped private CFG keeps them apart.
# The runtime enters them with runtime_invoke_private_entry_in_image().

"""


def load_map(path):
    with open(path, "rb") as f:
        m = tomllib.load(f)
    if m.get("schema") != 1:
        sys.exit(f"{path}: unsupported schema {m.get('schema')!r}")
    return m["image"]


def seeds_of(img):
    s = [(a, "arm") for a in img["seeds_arm"]] + [(a, "thumb") for a in img["seeds_thumb"]]
    return sorted(s)


def emit_config(images):
    out = [CONFIG_HEADER]
    for img in images:
        out.append(f'[[executable_image]]\nid = "{img["id"]}"\n'
                   f'path = "{PARTS_REL}/{img["part"]}.bin"\n'
                   f'load_address = 0x{img["load_address"]:08X}\nsize = 0x{img["size"]:X}\n'
                   f'sha256 = "{img["sha256"]}"\noverlay = true\n'
                   f'note = "NES emulator {img["part"]}"\n\n')
    for img in images:
        n, base, size = img["part"], img["load_address"], img["size"]
        out.append(f"# ---- {n}: 0x{base:08X}..0x{base + size:08X}\n")
        for a, b, m in img["runs"]:
            if m == "data":
                out.append(f'[[data_range]]\nstart = 0x{a:08X}\nend = 0x{b:08X}\n'
                           f'note = "NES {n} data/literals"\nimage = "{img["id"]}"\n\n')
        for a, m in seeds_of(img):
            out.append(f'[[extra_func]]\naddr = 0x{a:08X}\nmode = "{m}"\n'
                       f'name = "nes_{n}_{a:08x}"\ndispatch = false\n'
                       f'image = "{img["id"]}"\n\n')
    return "".join(out)


def gate_runs(img):
    cur, gate = img["load_address"], []
    for m in sorted(img.get("mutable", []), key=lambda r: r["start"]):
        if m["start"] > cur:
            gate.append((cur, m["start"]))
        cur = max(cur, m["end"])
    if cur < img["load_address"] + img["size"]:
        gate.append((cur, img["load_address"] + img["size"]))
    return gate


def emit_header(images, parts_dir):
    out = ["// Generated by scripts/generate-nes-emulator-config.py from",
           "// configs/nes-emulator-map-us.toml + the ROM-extracted Part images.",
           "// Addresses, modes and SHA-256 digests only; no ROM-derived bytes.",
           "// gate runs = whole image minus runtime-proven mutable data; the gate",
           "// SHA-256 covers those runs (code + literal pools baked into generated code).",
           "#pragma once\n#include <cstddef>\n#include <cstdint>\n",
           "namespace mzm_nes_emulator {\n",
           "struct CodeRun { std::uint32_t start; std::uint32_t end; };\n"]
    for img in images:
        n, base, size = img["part"], img["load_address"], img["size"]
        out.append("// Code runs from the decomp mapping symbols (test classification only).")
        out.append(f"inline constexpr CodeRun k_{n}_code[] = {{")
        out += [f"    {{0x{a:08X}u, 0x{b:08X}u}}," for a, b, m in img["runs"] if m != "data"]
        out.append("};")
        gate = gate_runs(img)
        with open(os.path.join(parts_dir, f"{n}.bin"), "rb") as f:
            blob = f.read()
        if len(blob) != size or hashlib.sha256(blob).hexdigest() != img["sha256"]:
            sys.exit(f"{n}: extracted image does not match canonical size/sha256")
        h = hashlib.sha256()
        for a, b in gate:
            h.update(blob[a - base:b - base])
        out.append(f"inline constexpr CodeRun k_{n}_gate[] = {{")
        out += [f"    {{0x{a:08X}u, 0x{b:08X}u}}," for a, b in gate]
        out.append("};")
        out.append(f'inline constexpr const char* k_{n}_gate_sha256 =\n    "{h.hexdigest()}";')
        first = b"".join(blob[a - base:b - base] for a, b in gate)[:32]
        out.append(f'inline constexpr const char* k_{n}_prefilter_sha256 =\n'
                   f'    "{hashlib.sha256(first).hexdigest()}";\n')
    out.append("}  // namespace mzm_nes_emulator")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--map", default=DEFAULT_MAP)
    ap.add_argument("--config-out")
    ap.add_argument("--header-out")
    ap.add_argument("--check-header", metavar="PATH")
    ap.add_argument("--parts-dir", default=PARTS_REL)
    args = ap.parse_args()
    if not (args.config_out or args.header_out or args.check_header):
        ap.error("nothing to do")
    images = load_map(args.map)
    if args.config_out:
        os.makedirs(os.path.dirname(os.path.abspath(args.config_out)), exist_ok=True)
        with open(args.config_out, "w", newline="\n") as f:
            f.write(emit_config(images))
        print(f"config written: {args.config_out}")
    if args.header_out:
        with open(args.header_out, "w", newline="\n") as f:
            f.write(emit_header(images, args.parts_dir))
        print(f"header written: {args.header_out}")
    if args.check_header:
        want = emit_header(images, args.parts_dir)
        with open(args.check_header) as f:
            have = f.read()
        if want != have:
            print(f"STALE: {args.check_header} differs from canonical map + extracted parts")
            return 1
        print(f"header up to date: {args.check_header}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
